import { spawn } from "node:child_process";
import path from "node:path";
import { db } from "./db.js";
import { loadRun, loadTicket } from "./store.js";
import { getRemoteUrl, pushBranch } from "./git.js";

export interface OpenPrResult {
  repo_name: string;
  pushed: boolean;
  push_output: string;
  pr_url: string | null;
  pr_method: "gh" | "compare-link" | "skipped";
  error?: string;
}

function ghAvailable(): Promise<boolean> {
  return new Promise((resolve) => {
    const c = spawn("gh", ["--version"], { stdio: "ignore" });
    c.on("error", () => resolve(false));
    c.on("close", (code) => resolve(code === 0));
  });
}

function ghPrCreate(args: {
  worktreePath: string;
  title: string;
  body: string;
  baseBranch: string;
}): Promise<{ ok: boolean; output: string }> {
  return new Promise((resolve) => {
    const c = spawn(
      "gh",
      ["pr", "create", "--base", args.baseBranch, "--title", args.title, "--body", args.body],
      { cwd: args.worktreePath, stdio: ["ignore", "pipe", "pipe"] },
    );
    let stdout = "";
    let stderr = "";
    c.stdout.on("data", (b) => (stdout += b.toString()));
    c.stderr.on("data", (b) => (stderr += b.toString()));
    c.on("error", (e) => resolve({ ok: false, output: e.message }));
    c.on("close", (code) =>
      resolve({ ok: code === 0, output: (stdout + stderr).trim() }),
    );
  });
}

function deriveCompareUrl(remoteUrl: string, baseBranch: string, branch: string): string | null {
  // git@github.com:org/repo.git or https://github.com/org/repo(.git)
  const m =
    remoteUrl.match(/github\.com[:/]+([^/]+)\/([^/.]+)(?:\.git)?$/) ||
    null;
  if (!m) return null;
  const [, org, repo] = m;
  return `https://github.com/${org}/${repo}/compare/${baseBranch}...${branch}?expand=1`;
}

export async function openPullRequests(runId: string): Promise<OpenPrResult[]> {
  const run = loadRun(runId);
  if (!run) throw new Error("run not found");
  if (run.status !== "succeeded") {
    throw new Error(`run is ${run.status}; only succeeded runs can open PRs`);
  }
  const ticket = loadTicket(run.ticket_id);
  if (!ticket) throw new Error("ticket not found");

  const repoRows = db
    .prepare("SELECT name, default_branch FROM repos WHERE project_id = ?")
    .all(run.project_id) as { name: string; default_branch: string }[];
  const baseBranchByRepo = new Map(repoRows.map((r) => [r.name, r.default_branch]));

  const ghOk = await ghAvailable();

  const title = ticket.title;
  const body = [
    ticket.body || "(no body)",
    "",
    "---",
    `Generated by ceo from ticket \`${ticket.id}\` (run \`${run.id}\`).`,
    ticket.triage_notes ? `\nTriage notes: ${ticket.triage_notes}` : "",
  ].join("\n");

  return Promise.all(
    run.worktrees.map(async (wt): Promise<OpenPrResult> => {
      const baseBranch = baseBranchByRepo.get(wt.repo_name) ?? "main";
      const push = await pushBranch(wt.path, run.branch);
      if (!push.ok) {
        return {
          repo_name: wt.repo_name,
          pushed: false,
          push_output: push.output,
          pr_url: null,
          pr_method: "skipped",
          error: "push failed",
        };
      }

      if (ghOk) {
        const r = await ghPrCreate({
          worktreePath: wt.path,
          title,
          body,
          baseBranch,
        });
        if (r.ok) {
          // gh prints the PR URL on the first line of stdout.
          const url = r.output.split("\n").find((l) => l.startsWith("http"))?.trim() ?? null;
          return {
            repo_name: wt.repo_name,
            pushed: true,
            push_output: push.output,
            pr_url: url,
            pr_method: "gh",
          };
        }
      }

      const remote = await getRemoteUrl(wt.path);
      const compareUrl = remote ? deriveCompareUrl(remote, baseBranch, run.branch) : null;
      return {
        repo_name: wt.repo_name,
        pushed: true,
        push_output: push.output,
        pr_url: compareUrl,
        pr_method: "compare-link",
      };
    }),
  );
}
